modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mechcraft"
version="1.0.0"
displayName="MechCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Nikita, MCreator"

[[dependencies.mechcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




